version: 2

project_name: cio

builds:
  - binary: cio
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/leechael/cio/cmd.version={{.Version}}
      - -X github.com/leechael/cio/cmd.commit={{.Commit}}
      - -X github.com/leechael/cio/cmd.date={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
